version: 0.0
Resources:
  - MyLambdaFunction:
      Type: AWS::Lambda::Function
      Properties:
        Name: "aws-practice-lambda"     # CHANGE to your Lambda function name
        Alias: "prod"                   # CodeDeploy will shift traffic on this alias
Hooks:
  BeforeAllowTraffic:
    - location: scripts/before_allow_traffic.sh
      timeout: 300
  AfterAllowTraffic:
    - location: scripts/after_allow_traffic.sh
      timeout: 300
